### PR TITLE
Update Tock submodule

### PR DESCRIPTION
**Pull request by bradjc**
This PR updates the Tock submodule to a recent commit. To make this compile includes:

- Using the tock version of the register interface which is slightly different syntactically.
- Using NVIC for the interrupt queue rather than a dedicated structure.
- Updating to slight changes in paths/names for the kernel crate.

I don't have a teensy so I can't test, so help would be appreciated there.

### CODE REVIEW

**Comment by alevy** [comment]
Maybe @rminnich can review this?

**Comment by cmcavity** [comment]
I ran the tests in boards/teensy/src/tests by running make program, and all of them were successful except for the blink::blink_test(), which failed during compilation.

I've attached a screenshot of the error that I got.

image

**Comment by bradjc** [comment]
Can you provide more details on what commit you were trying to compile with? That error looks like the compiler was removing things it shouldn't.

**Comment by cmcavity** [comment]
This was commit 4305c2e, the most recent commit on the update-tock-master branch.

**Comment by cmcavity** [comment]
The test compiles and passes successfully when I replace the `loop {}` on line 15 of boards/teensy/src/tests/blink.rs with a for loop in an unsafe block. I'm not sure how to interpret this.

**Comment by bradjc** [comment]
I looked into this for a minute, and I'm not sure what is going on. Given you have a workaround and it is a pretty simple test, I'm inclined to ignore it and push ahead.

**Comment by cmcavity** [comment]
Another issue is that the example apps no longer compile because they rely on libtock, which has since been moved from tock to libtock-c. Would it be more appropriate to add libtock-c as a second submodule to tock-teensy, or to move the tock-teensy example apps to a separate repository?

**Comment by bradjc** [comment]
Is the plan to move the teensy board to tock proper?

**Comment by cmcavity** [comment]
It's not the current plan - @phil-levis suggested that we just add libtock-c as a submodule for now.

**Comment by bradjc** [comment]
Merging this with a follow up PR coming to sort out any lingering issues.

**Pull request merged**
